apiVersion: v1
kind: Pod
metadata:
  name: insecure-attacker-pod
spec:
  containers:
    - name: hacked-container
      image: nginx:latest
      securityContext:
        privileged: true
        runAsUser: 0